"use client";

import type { ChangeEvent, FormEvent } from "react";
import { useState } from "react";

type RiskLevel = "low" | "medium" | "high";

type DocumentStats = {
  filename: string;
  content_type: string;
  size_bytes: number;
  characters: number;
  words: number;
  paragraphs: number;
  blocks: number;
};

type AnalysisSummary = {
  overall_risk: RiskLevel;
  total_risk_score: number;
  high_risk_blocks: number;
  medium_risk_blocks: number;
  low_risk_blocks: number;
  cliches_total: number;
  abstract_words_total: number;
};

type RiskSentence = {
  sentence_index: number;
  sentence: string;
  markers: string[];
};

type BlockAnalysis = {
  block_name: string;
  words: number;
  characters: number;
  sentences: number;
  avg_sentence_len: number;
  sentence_len_std: number;
  cliches_count: number;
  abstract_words_count: number;
  risk_score: number;
  risk_level: RiskLevel;
  risky_sentences: RiskSentence[];
};

type AnalyzeResponse = {
  status: "analyzed";
  document: DocumentStats;
  summary: AnalysisSummary;
  blocks: BlockAnalysis[];
  limitations: string[];
};

const API_URL = "http://localhost:8000/api/v1/analyze";

const riskLabels: Record<RiskLevel, string> = {
  low: "Низкий",
  medium: "Средний",
  high: "Высокий",
};

const riskClassNames: Record<RiskLevel, string> = {
  low: "border-emerald-500/30 bg-emerald-500/10 text-emerald-200",
  medium: "border-amber-500/30 bg-amber-500/10 text-amber-200",
  high: "border-red-500/30 bg-red-500/10 text-red-200",
};

const limitationTranslations: Record<string, string> = {
  "The tool does not prove that a text was generated by AI.":
    "Инструмент не доказывает, что текст был сгенерирован нейросетью.",
  "The result is an editorial risk assessment based on linguistic and structural markers.":
    "Результат является редакционной оценкой риска по языковым и структурным признакам.",
  "Russian academic texts may produce false positives because of formal style and repeated terminology.":
    "Русские академические тексты могут давать ложные срабатывания из-за формального стиля и повторяющейся терминологии.",
};

function formatBytes(bytes: number): string {
  if (bytes < 1024) {
    return `${bytes} Б`;
  }

  if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} КБ`;
  }

  return `${(bytes / 1024 / 1024).toFixed(1)} МБ`;
}

export function AnalyzerUploadForm() {
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<AnalyzeResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  function handleFileChange(event: ChangeEvent<HTMLInputElement>) {
    const selectedFile = event.target.files?.[0] ?? null;

    setFile(selectedFile);
    setResult(null);
    setError(null);
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!file) {
      setError("Выберите DOCX-файл для анализа.");
      return;
    }

    const formData = new FormData();
    formData.append("file", file);

    setIsLoading(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch(API_URL, {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.detail ?? "Не удалось выполнить анализ документа.");
        return;
      }

      setResult(data as AnalyzeResponse);
    } catch {
      setError(
        "API недоступен. Проверьте, что FastAPI backend запущен на localhost:8000.",
      );
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <section className="w-full max-w-6xl">
      <form
        onSubmit={handleSubmit}
        className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 shadow-2xl shadow-black/20"
      >
        <div className="flex flex-col gap-4 md:flex-row md:items-end">
          <label className="flex flex-1 flex-col gap-2">
            <span className="text-sm font-medium text-slate-200">
              DOCX-документ
            </span>
            <input
              type="file"
              accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
              onChange={handleFileChange}
              className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3 text-sm text-slate-200 file:mr-4 file:rounded-xl file:border-0 file:bg-slate-100 file:px-4 file:py-2 file:text-sm file:font-medium file:text-slate-950"
            />
          </label>

          <button
            type="submit"
            disabled={!file || isLoading}
            className="rounded-2xl bg-slate-100 px-6 py-3 text-sm font-semibold text-slate-950 transition hover:bg-white disabled:cursor-not-allowed disabled:opacity-50"
          >
            {isLoading ? "Анализ..." : "Проверить документ"}
          </button>
        </div>

        {file ? (
          <p className="mt-4 text-sm text-slate-400">
            Выбран файл: <span className="text-slate-200">{file.name}</span>
          </p>
        ) : null}

        {error ? (
          <div className="mt-4 rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">
            {error}
          </div>
        ) : null}
      </form>

      {result ? (
        <div className="mt-8 space-y-6">
          <div className="grid gap-4 md:grid-cols-4">
            <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5">
              <p className="text-sm text-slate-400">Общий риск</p>
              <p
                className={`mt-3 inline-flex rounded-full border px-3 py-1 text-sm font-semibold ${
                  riskClassNames[result.summary.overall_risk]
                }`}
              >
                {riskLabels[result.summary.overall_risk]}
              </p>
            </div>

            <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5">
              <p className="text-sm text-slate-400">Слов</p>
              <p className="mt-3 text-3xl font-semibold text-white">
                {result.document.words}
              </p>
            </div>

            <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5">
              <p className="text-sm text-slate-400">Блоков</p>
              <p className="mt-3 text-3xl font-semibold text-white">
                {result.document.blocks}
              </p>
            </div>

            <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-5">
              <p className="text-sm text-slate-400">Размер</p>
              <p className="mt-3 text-3xl font-semibold text-white">
                {formatBytes(result.document.size_bytes)}
              </p>
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6">
            <h2 className="text-xl font-semibold text-white">
              Сводка анализа
            </h2>

            <dl className="mt-4 grid gap-4 text-sm md:grid-cols-3">
              <div>
                <dt className="text-slate-400">Высокий риск</dt>
                <dd className="mt-1 text-lg font-semibold text-white">
                  {result.summary.high_risk_blocks}
                </dd>
              </div>
              <div>
                <dt className="text-slate-400">Средний риск</dt>
                <dd className="mt-1 text-lg font-semibold text-white">
                  {result.summary.medium_risk_blocks}
                </dd>
              </div>
              <div>
                <dt className="text-slate-400">Низкий риск</dt>
                <dd className="mt-1 text-lg font-semibold text-white">
                  {result.summary.low_risk_blocks}
                </dd>
              </div>
              <div>
                <dt className="text-slate-400">Клише</dt>
                <dd className="mt-1 text-lg font-semibold text-white">
                  {result.summary.cliches_total}
                </dd>
              </div>
              <div>
                <dt className="text-slate-400">Абстрактные слова</dt>
                <dd className="mt-1 text-lg font-semibold text-white">
                  {result.summary.abstract_words_total}
                </dd>
              </div>
              <div>
                <dt className="text-slate-400">Суммарный балл риска</dt>
                <dd className="mt-1 text-lg font-semibold text-white">
                  {result.summary.total_risk_score}
                </dd>
              </div>
            </dl>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6">
            <h2 className="text-xl font-semibold text-white">Блоки текста</h2>

            <div className="mt-4 overflow-hidden rounded-2xl border border-white/10">
              <table className="w-full border-collapse text-left text-sm">
                <thead className="bg-white/[0.06] text-slate-300">
                  <tr>
                    <th className="px-4 py-3">Блок</th>
                    <th className="px-4 py-3">Риск</th>
                    <th className="px-4 py-3">Балл</th>
                    <th className="px-4 py-3">Слова</th>
                    <th className="px-4 py-3">Клише</th>
                    <th className="px-4 py-3">Абстр.</th>
                  </tr>
                </thead>
                <tbody>
                  {result.blocks.map((block) => (
                    <tr key={block.block_name} className="border-t border-white/10">
                      <td className="px-4 py-3 text-slate-200">
                        {block.block_name}
                      </td>
                      <td className="px-4 py-3">
                        <span
                          className={`rounded-full border px-2 py-1 text-xs font-semibold ${
                            riskClassNames[block.risk_level]
                          }`}
                        >
                          {riskLabels[block.risk_level]}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-slate-300">
                        {block.risk_score}
                      </td>
                      <td className="px-4 py-3 text-slate-300">{block.words}</td>
                      <td className="px-4 py-3 text-slate-300">
                        {block.cliches_count}
                      </td>
                      <td className="px-4 py-3 text-slate-300">
                        {block.abstract_words_count}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="rounded-3xl border border-white/10 bg-white/[0.04] p-6">
            <h2 className="text-xl font-semibold text-white">
              Ограничения метода
            </h2>
            <ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-slate-400">
              {result.limitations.map((limitation) => (
                <li key={limitation}>
                  {limitationTranslations[limitation] ?? limitation}
                </li>
              ))}
            </ul>
          </div>
        </div>
      ) : null}
    </section>
  );
}
