from typing import Annotated

from fastapi import APIRouter, File, HTTPException, UploadFile

from docx_ai_risk_api.analyzer.extraction import (
    DocumentExtractionError,
    extract_text_from_docx_bytes,
)
from docx_ai_risk_api.analyzer.heuristics import analyze_text, count_words, split_paragraphs
from docx_ai_risk_api.schemas import AnalysisSummary, AnalyzeResponse, DocumentStats

router = APIRouter()


@router.post("/analyze", response_model=AnalyzeResponse)
async def analyze_document(file: Annotated[UploadFile, File()]) -> AnalyzeResponse:
    if not file.filename:
        raise HTTPException(status_code=400, detail="Filename is required")

    if not file.filename.lower().endswith(".docx"):
        raise HTTPException(status_code=400, detail="Only .docx files are supported")

    content = await file.read()

    if not content:
        raise HTTPException(status_code=400, detail="Uploaded file is empty")

    try:
        text = extract_text_from_docx_bytes(content)
    except DocumentExtractionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    blocks = analyze_text(text)

    high_risk_blocks = sum(1 for block in blocks if block.risk_level == "high")
    medium_risk_blocks = sum(1 for block in blocks if block.risk_level == "medium")
    low_risk_blocks = sum(1 for block in blocks if block.risk_level == "low")

    if high_risk_blocks:
        overall_risk = "high"
    elif medium_risk_blocks:
        overall_risk = "medium"
    else:
        overall_risk = "low"

    document = DocumentStats(
        filename=file.filename,
        content_type=file.content_type or "unknown",
        size_bytes=len(content),
        characters=len(text),
        words=count_words(text),
        paragraphs=len(split_paragraphs(text)),
        blocks=len(blocks),
    )

    summary = AnalysisSummary(
        overall_risk=overall_risk,
        total_risk_score=sum(block.risk_score for block in blocks),
        high_risk_blocks=high_risk_blocks,
        medium_risk_blocks=medium_risk_blocks,
        low_risk_blocks=low_risk_blocks,
        cliches_total=sum(block.cliches_count for block in blocks),
        abstract_words_total=sum(block.abstract_words_count for block in blocks),
    )

    return AnalyzeResponse(
        document=document,
        summary=summary,
        blocks=blocks,
        limitations=[
            "The tool does not prove that a text was generated by AI.",
            (
                "The result is an editorial risk assessment based on linguistic "
                "and structural markers."
            ),
            (
                "Russian academic texts may produce false positives because "
                "of formal style and repeated terminology."
            ),
        ],
    )
